name: nanc_analytics
description: A new Flutter package project.
version: 0.0.1
homepage: nope
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.10.1"

dependencies:
  flutter:
    sdk: flutter
  nanc_configuration:
    path: ../../nanc/nanc_configuration
  nanc_tools:
    path: ../../nanc/nanc_tools
  amplitude_flutter: ^3.14.0
  go_router: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints:
    path: ../../nanc/nanc_lints

flutter: