name: nanc_backend
description: Nanc project backend demo
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.10.1"

dependencies:
  flutter:
    sdk: flutter
  nanc: ^0.0.4
  nanc_webrtc:
    path: ../nanc_webrtc
  nanc_tools: ^0.0.3
  nanc_icons: ^0.0.1
  animation_debugger: ^1.0.0
  components:
    path: ../components
  additions:
    path: ../additions
  nanc_analytics: ^0.0.1
  nanc_fonts: ^0.0.1
  nanc_configuration: ^0.0.3
  nui_svg_renderer: ^1.0.0
  cupertino_icons: ^1.0.5
  pretty_qr_code: ^2.0.3
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  copy_with_extension: ^6.0.1
  path_provider: ^2.1.5
  path: ^1.9.1
  autoequal: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints: ^1.0.0
  json_serializable: ^6.9.5
  copy_with_extension_gen: ^6.0.1
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.13.1
  autoequal_gen: ^0.9.5

dependency_overrides:
  analyzer: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: Blazeface
      fonts:
        - asset: assets/fonts/blazeface.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helvetica.ttf
          weight: 400
        - asset: assets/fonts/helvetica_light.ttf
          weight: 300
        - asset: assets/fonts/helvetica_bold.ttf
          weight: 500
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/helvetica_neue_wide.ttf
          weight: 400
        - asset: assets/fonts/helvetica_neue_light.ttf
          weight: 300

# flutter pub run flutter_launcher_icons
flutter_icons:
  image_path: "assets/full.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/full.png"
  macos:
    generate: true
    image_path: "assets/full.png"