name: introduction_cms
description: Introduction CMS
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0-42.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  nanc:
    path: ../../nanc/nanc
  nanc_configuration:
    path: ../../nanc/nanc_configuration
  nanc_api_local:
    path: ../../nanc/nanc_api_local
  nanc_api_firebase:
    path: ../../nanc/nanc_api_firebase
  nanc_api_supabase:
    path: ../../nanc/nanc_api_supabase
  additions:
    path: ../additions
  nanc_tools:
    path: ../../nanc/nanc_tools
  nanc_icons:
    path: ../../nanc/nanc_icons
  svg_renderer:
    path: ../../nanc/svg_renderer
  nanc_fonts:
    path: ../../nanc/nanc_fonts
  nui:
    path: ../../nanc/nui
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints:
    path: ../../nanc/nanc_lints

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: Blazeface
      fonts:
        - asset: assets/fonts/blazeface.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helvetica.ttf
          weight: 400
        - asset: assets/fonts/helvetica_light.ttf
          weight: 300
        - asset: assets/fonts/helvetica_bold.ttf
          weight: 500
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/helvetica_neue_wide.ttf
          weight: 400
        - asset: assets/fonts/helvetica_neue_light.ttf
          weight: 300