name: performance
description: Performance overlay package for Flutter apps that works on web.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.2.0-42.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints: ^1.0.0

