name: nanc_webrtc
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.10.1"

dependencies:
  flutter:
    sdk: flutter
  nanc_tools: ^0.0.3
  dio: ^5.8.0
  json_annotation: ^4.9.0
  copy_with_extension: ^6.0.1
  peerdart: ^0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints: ^1.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  copy_with_extension_gen: ^6.0.1

dependency_overrides:
  analyzer: ^7.0.0

flutter: