name: components
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.10.1"

dependencies:
  flutter:
    sdk: flutter
  nanc_icons:
    path: ../../nanc/nanc_icons
  nui:
    path: ../../nanc/nui
  nanc_tools:
    path: ../../nanc/nanc_tools
  json_annotation: ^4.8.1
  copy_with_extension: ^5.0.2
  carousel_slider: ^4.2.1

dev_dependencies:
  nanc_lints:
    path: ../../nanc/nanc_lints
  json_serializable: ^6.7.0
  copy_with_extension_gen: ^5.0.2
  build_runner: ^2.4.4

flutter: