name: introduction_app
description: Introduction App, built on Nanc Backend Driven UI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0-42.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  nanc_renderer:
    path: ../../nanc/nanc_renderer
  nanc_fonts:
    path: ../../nanc/nanc_fonts
  nanc_icons:
    path: ../../nanc/nanc_icons
  svg_renderer:
    path: ../../nanc/svg_renderer
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints:
    path: ../../nanc/nanc_lints

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: Blazeface
      fonts:
        - asset: assets/fonts/blazeface.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helvetica.ttf
          weight: 400
        - asset: assets/fonts/helvetica_light.ttf
          weight: 300
        - asset: assets/fonts/helvetica_bold.ttf
          weight: 500
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/helvetica_neue_wide.ttf
          weight: 400
        - asset: assets/fonts/helvetica_neue_light.ttf
          weight: 300