name: introduction_app
description: Introduction App, built on Nanc Backend Driven UI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0-42.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  nui: ^0.0.2
  nanc_fonts: ^0.0.1
  nanc_icons: ^0.0.1
  nanc_tools: ^0.0.2
  nui_svg_renderer: ^1.0.0
  ionicons: ^0.2.2
  flutter_svg: ^2.0.10+1
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  equatable: ^2.0.5
  autoequal: ^0.9.1
  copy_with_extension: ^5.0.4
  performance:
    path: ../performance

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints: ^1.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  autoequal_gen: ^0.9.1
  copy_with_extension_gen: ^5.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/data/
  fonts:
    - family: Blazeface
      fonts:
        - asset: assets/fonts/blazeface.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helvetica.ttf
          weight: 400
        - asset: assets/fonts/helvetica_light.ttf
          weight: 300
        - asset: assets/fonts/helvetica_bold.ttf
          weight: 500
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/helvetica_neue_wide.ttf
          weight: 400
        - asset: assets/fonts/helvetica_neue_light.ttf
          weight: 300