name: nanc_demo_cms
description: Demo Nanc CMS
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.10.1"

dependencies:
  flutter:
    sdk: flutter
  nanc:
    path: ../../nanc/nanc
  nanc_api_supabase:
    path: ../../nanc/nanc_api_supabase
  nanc_api_firebase:
    path: ../../nanc/nanc_api_firebase
  nanc_configuration:
    path: ../../nanc/nanc_configuration
  nanc_icons:
    path: ../../nanc/nanc_icons

  firebase_core: any
dev_dependencies:
  nanc_lints:
    path: ../../nanc/nanc_lints

flutter:
  uses-material-design: true