name: nanc_client
description: Nanc project demo client
publish_to: 'none'
version: 0.0.1+5

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.10.1"

dependencies:
  flutter:
    sdk: flutter
  nanc_webrtc:
    path: ../nanc_webrtc
  nanc_tools:
    path: ../../nanc/nanc_tools
  nanc:
    path: ../../nanc/nanc
  nanc_renderer:
    path: ../../nanc/nanc_renderer
  nanc_icons:
    path: ../../nanc/nanc_icons
  additions:
    path: ../additions
  components:
    path: ../components
  analytics:
    path: ../../nanc/analytics
  cupertino_icons: ^1.0.5
  nanc_fonts:
    path: ../../nanc/nanc_fonts
  svg_renderer:
    path: ../../nanc/svg_renderer
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  copy_with_extension: ^5.0.2
  vrouter: ^1.2.1
  device_frame: ^1.1.0
  mobile_scanner: ^3.2.0
  dio: ^5.1.2
  autoequal: ^0.9.1

#dependency_overrides:
#  mobile_scanner:
#    git:
#      url: https://github.com/juliansteenbakker/mobile_scanner
#      ref: bug/fix-macos

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints:
    path: ../../nanc/nanc_lints
  json_serializable: ^6.7.0
  copy_with_extension_gen: ^5.0.2
  build_runner: ^2.4.4
  flutter_launcher_icons: ^0.13.1
  autoequal_gen: ^0.9.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: Blazeface
      fonts:
        - asset: assets/fonts/blazeface.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helvetica.ttf
          weight: 400
        - asset: assets/fonts/helvetica_light.ttf
          weight: 300
        - asset: assets/fonts/helvetica_bold.ttf
          weight: 500
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/helvetica_neue_wide.ttf
          weight: 400
        - asset: assets/fonts/helvetica_neue_light.ttf
          weight: 300

# flutter pub run flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/full.png"
  adaptive_icon_background: "assets/back.png"
  adaptive_icon_foreground: "assets/front.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/full.png"
    background_color: "#C3E3E5"
    theme_color: "#C3E3E5"
  macos:
    generate: true
    image_path: "assets/full.png"